### ISSUE TITLE
Add enabling mdex port with enabled selinux

### ISSUE THREAD

**Issue by anastacia-maletskaya-epam** [lean-delivery/ansible-role-endeca-mdex#2]
##### SUMMARY

Add enabling mdex port (default 8000) with enabled selinux

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

seport

##### ANSIBLE VERSION

```
2.5.7
```

##### OS / ENVIRONMENT

Cento 6/7

**Comment by anastacia-maletskaya-epam** [comment]
Submitted bug for seport module https://github.com/ansible/ansible/issues/49050

**Comment by vnovichek** [comment]
I'd like to chime in with some news. Just played a bit with the issue using ansible 2.4, 2.5, 2.7 and the answer is it doesn't depend on the ansible version but on the AWS shape. In case of micro shape, OOM killer kills the python process. And I haven't got an error if medium shape was used.

**Comment by vutkin** [comment]
fixed
